source "$_orb_root/scripts/initialize_variables.sh"

source "$_orb_root/functions/utils/pass.sh"
source "$_orb_root/functions/utils/param_token.sh"
source "$_orb_root/functions/utils/debug.sh"
source "$_orb_root/functions/utils/error.sh"
source "$_orb_root/functions/utils/file.sh"
source "$_orb_root/functions/utils/text.sh"
source "$_orb_root/functions/utils/utils.sh"

source "$_orb_root/functions/call/libraries.sh"
source "$_orb_root/functions/call/settings.sh"
source "$_orb_root/functions/call/namespace.sh"
source "$_orb_root/functions/call/function.sh"

source "$_orb_root/functions/declaration/function.sh"
source "$_orb_root/functions/declaration/function_options.sh"
source "$_orb_root/functions/declaration/params.sh"
source "$_orb_root/functions/declaration/param_options.sh"
source "$_orb_root/functions/declaration/checkers.sh"
source "$_orb_root/functions/declaration/getters.sh"
source "$_orb_root/functions/declaration/settings_declaration.sh"
source "$_orb_root/functions/declaration/validation.sh"

source "$_orb_root/functions/argument/assignment.sh"
source "$_orb_root/functions/argument/collection.sh"
source "$_orb_root/functions/argument/defaults.sh"
source "$_orb_root/functions/argument/getters.sh"
source "$_orb_root/functions/argument/positional.sh"
source "$_orb_root/functions/argument/store.sh"
source "$_orb_root/functions/argument/validation.sh"

source "$_orb_root/functions/call/help_orb.sh"
source "$_orb_root/functions/call/help_namespace.sh"
source "$_orb_root/functions/call/help_function.sh"
